### ISSUE TITLE
create nodejs server as server folder

### ISSUE THREAD

**Issue by adeniranjohn** [BuildForSDGCohort2/team-024-group-a#2]
Create a nodejs server

**Comment by samuelhenshaw2020** [comment]
I have created the nodejs backend application. in the checklist are
1. install express framework and necessary dependencies such as morgan (for logging), dotenv (for creating environment variable - .env), bodyparser (for json data manipulation)
2. set local variable with the .env file
3. use cluster module to fork the app to use available CPU
4. setup the express server to listen on designated port
