### ISSUE TITLE
host backend via Netlify, Firebase, AWS, Heroku

### ISSUE THREAD

**Issue by adeniranjohn** [BuildForSDGCohort2/team-024-group-a#23]
Go through 

Netlify
Firebase
AWS
Heroku

Give the url for frontend fetch from the address

**Comment by samuelhenshaw2020** [comment]
Ok Netlify on the way.

Please i need authorization to use allow netlify gain access to the backed repo

**Comment by adeniranjohn** [comment]
We have to use heroku for the backend api
**https://calm-taiga-84530.herokuapp.com/**
