### ISSUE TITLE
create routes for

### ISSUE THREAD

**Issue by adeniranjohn** [BuildForSDGCohort2/team-024-group-a#7]
-client
-doctors
-diagnostic centers
-hospitals

**Comment by samuelhenshaw2020** [comment]
just created a welcome route : "/api"

**Comment by samuelhenshaw2020** [comment]
creating routes

**Comment by samuelhenshaw2020** [comment]
I have created the route for doctors, diagnostic centers, hospitals, and clients. However, i have an additional route called guest - for unauthenticated users.
